### ISSUE TITLE
Keep translated strings empty

### ISSUE THREAD

**Issue by grcasanova** [amiranagram/localizator#11]
Excellent package!
A minor change needed, when generating lists for languages other than the default one, keep the translated string empty.

**Example**
```
default lang = en
__('Account settings')
```
```
en.json
"Account settings": "Account settings",

de.json
"Account settings": "",
```
instead of
```
de.json
"Account settings": "Account settings",
```

**Comment by amiranagram** [comment]
Good idea, will include it in the upcoming release.
