### ISSUE TITLE
Delete a key that no longer exists

### ISSUE THREAD

**Issue by RafaleD** [amiranagram/localizator#26]
Hello.

Is it possible that the extraction script automatically deletes the keys that no longer exist? 

Example: A .blade.php file contained a string 'test'. This string doesn't exist anymore (it has been deleted from balde.php). Is it possible that it is automatically removed from the lang files so that we have a version that is always up to date and does not have a key that no longer exists?

**Comment by amiranagram** [comment]
Not currently, but It's a good feature that I can add, so we can have something like:

```bash
php artisan localize de,ru,es --remove-missing
```

Thanks for the suggestion.

**Comment by RafaleD** [comment]
Awesome, this would be a great feature !
