### ISSUE TITLE
Default writer not working

### ISSUE THREAD

**Issue by oulfr** [amiranagram/localizator#27]
Hello,
thank you for this nice package.
in the configuration file i have default=true and when i run the command: 

php artisan localize de

In the ressource/lang there is just json file not .php ? 

I have missing something ?

**Comment by amiranagram** [comment]
PHP files are stored inside folders, so it should be inside `resources/lang/de`. Or maybe I'm missing the point. Can you give more info?

**Comment by oulfr** [comment]
i have installed the plugin and run it in one of my folders, the json file is correctly generated but the php array folder is created under resources/lang/de but empty

**Comment by amiranagram** [comment]
Few questions for me to debug your issue:

1. What is the value of your `app.locale` config?
2. Is there any other languages in your project? Is `resources/lang/en` present or have you deleted that?
3. What is the value of your `localizator.search` config?

**Comment by oulfr** [comment]
What is the value of your app.locale config?
fr
Is there any other languages in your project? Is resources/lang/en present or have you deleted that?
all file deleted
What is the value of your localizator.search config?
        
               'search'   => [
                          /**
                           * Directories which should be looked inside.
                           */
                          'dirs'      => ['Modules/User'],
              
                          /**
                           * Patterns by which files should be queried.
                           * The values can be a regular expression, glob, or just a string.
                           */
                          'patterns'  => ['*.php'],
              
                      /**
                       * Functions that the strings will be extracted from.
                       * Add here any custom defined functions.
                       * NOTE: The translation string should always be the first argument.
                       */
                      'functions' => ['__', 'trans', '@lang']
                  ],

**Comment by oulfr** [comment]
I have installed : https://github.com/nWidart/laravel-modules
I have many modules in the Modules when i try with the first modules it work perfectlly but the second, third, ... no result maybe its a bug in laravel-modules i will debug to see what happen

**Comment by amiranagram** [comment]
I have tried to simulate over the weekend, but I couldn't. Any chance you can share your project with me, so I can have a look?
