### ISSUE TITLE
Missing compatibility with Laravel 9

### ISSUE THREAD

**Issue by fbsanchez** [amiranagram/localizator#30]
Hello!

This utility is no longer compatible with laravel 9

![image](https://user-images.githubusercontent.com/12999095/153379510-382ca194-7924-466e-a220-0f12051dde54.png)

Is it planned to be updated? Its been so long from latest code update...

Thanks!

**Comment by fbsanchez** [comment]
Great! thank you

**Comment by amiranagram** [comment]
#32

**Comment by fbsanchez** [comment]
Thank you @amiranagram working like a charm!
