### ISSUE TITLE
JS Support

### ISSUE THREAD

**Issue by rexlManu** [amiranagram/localizator#34]
Hey, I used this package also for inertiajs with the https://github.com/xiCO2k/laravel-vue-i18n package.

I added $t to the pattern and it works but the regex don't check for examples like this:

```
$t(
     'some random translatable message'
)
```

I adjusted the regex and asking if I should make pr with that, if you planned support for js?

**Comment by amiranagram** [comment]
Hi @rexlManu, when I wrote this package I planned to support custom functions (not only for PHP-Laravel), that's why I left the `functions` in config as customizable.

I will check out your PR though, and if everything is fine, I'll go ahead and merge. Thanks
