### ISSUE TITLE
How to ignore folder

### ISSUE THREAD

**Issue by william-koffi** [amiranagram/localizator#38]
I want to ignore all files in the resources/views/vendor folder.

**Comment by amiranagram** [comment]
hi @william-koffi, you can add a pattern to `localizator.search.patterns` that will be used to ignore files from the vendor folder.

**Comment by mrleblanc101** [comment]
Would it be possible to add an `ignore` option for folder ?
For exemple, we have a vendor/nova folder which is translated with PHP shortkey.
But the Blade file are translated with JSON and fallback text.

**Comment by mrleblanc101** [comment]
So in config instead of `search.dirs`, maybe `search.include` and `search.exclude`

**Comment by amiranagram** [comment]
I added the exclude options, which is basically an array of directories that will be excluded relative to the directories in `search.dirs`.

Example:

```php
'dirs'      => ['resources/views'],
'exclude' => ['vendor'],
```

Here, `vendor` directory will be excluded from `resources/views`.
