### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by Cluster2a** [amiranagram/localizator#59]
Hey there -  are there any plans on supporting Laravel 11?

**Comment by amiranagram** [comment]
There are, I will release it soon.

**Comment by hichxm** [comment]
See pull request https://github.com/amiranagram/localizator/pull/60

**Comment by Cluster2a** [comment]
@amiranagram, is there some ETA? This is the last package we need to continue with the update. :)

**Comment by amiranagram** [comment]
Released in 0.13.
