### ISSUE TITLE
cannot install on app based on  laravel 6.x LTS

### ISSUE THREAD

**Issue by marco-acorte** [amiranagram/localizator#7]
in composer.json require
 
`"illuminate/contracts": "^8.0"`

it's mandatory ?

because it's not working on laravel 6.x LTS

**Comment by amiranagram** [comment]
I'm planning to make it backwards compactible, since I also have a Laravel app running on 6.x LTS. So it's gonna be:
`"illuminate/contracts": "^8.0"`
`"php": "^7.2"`

I will also test it on PHP 8.0. Stay tuned.

**Comment by amiranagram** [comment]
I've released v0.3-alpha with support for Laravel 6.x LTS, check it out.

Additionally should work on any Laravel/PHP combinations tested here:
https://github.com/amiranagram/localizator/actions/runs/458013096

Cheers.
